---
# Task to export credential

- name: "Export asset - credential {{ item.name }}"
  awx.awx.export:
    credentials: "{{ item.name }}"
    controller_host: "{{ controller_host }}"
    controller_username: "{{ controller_username }}"
    controller_password: "{{ controller_password }}"
    validate_certs: false
  register: result

# - debug:
#     var: result.assets

- name: "Write asset json to local file {{ item.path }}"
  copy:
    content: "{{ result.assets | to_nice_json(indent=2) }}"
    dest: "{{ item.path }}.j2"
  delegate_to: 127.0.0.1
  when: backup_type == "json"

- name: "Write asset yaml to local file {{ item.path }}"
  copy:
    content: "{{ result.assets | to_nice_yaml(indent=2) }}"
    dest: "{{ item.path }}.j2"
  delegate_to: 127.0.0.1
  when: backup_type == "yml"

- name: "Create parameterized file for import - {{ item.name }}"
  block:
    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    vault_id:"
        line: "    vault_id: {% raw %}'{{ vault_id_value }}'{% endraw %}"
    
    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    vault_password:"
        line: "    vault_password: {% raw %}'{{ vault_password_value }}'{% endraw %}"
  delegate_to: 127.0.0.1
  when: item.type == "vault"

- name: "Create parameterized file for import - {{ item.name }}"
  block:
    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    become_username:"
        line: "    become_username: {% raw %}'{{ become_username_value }}'{% endraw %}"
    
    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    become_method:"
        line: "    become_method: {% raw %}'{{ become_method_value }}'{% endraw %}"

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    password:"
        line: "    password: {% raw %}'{{ password_value }}'{% endraw %}"

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    username:"
        line: "    username: {% raw %}'{{ username_value }}'{% endraw %}"
  delegate_to: 127.0.0.1
  when: item.type == "machine"

- name: "Create parameterized file for import - {{ item.name }}"
  block:
    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    password:"
        line: "    password: {% raw %}'{{ password_value }}'{% endraw %}"

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}.j2"
        regexp: "^    username:"
        line: "    username: {% raw %}'{{ username_value }}'{% endraw %}"
  delegate_to: 127.0.0.1
  when: item.type == "scc"

